/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class ATaskSchedulingProblem {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a,b,c;
    int ans = 0;
    //string ans = "";
    cin >> a >> b >>c;
    vector<int> v;
    v.push_back(abs(a-b));
    v.push_back(abs(a-c));
    v.push_back(abs(b-c));
    sort(v.begin(), v.end());
    ans = v.at(0) + v.at(1);
    cout << ans << endl;
}
};


int main() {
	ATaskSchedulingProblem solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
