/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class AABD {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a;
    string ans = "ABC";
    cin >> a;
    if(a>=1000) ans = "ABD";
    cout << ans << endl;
}
};


int main() {
	AABD solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
