/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class AMultipleOf2AndN {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a;
    int ans = 0;
    //string ans = "";
    cin >> a;
    if (a%2==0){
        ans = a;
    }else{
        ans = a*2;
    }

    cout << ans << endl;
}
};


int main() {
	AMultipleOf2AndN solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
