/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class ARatedForMe {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a;
    //int ans = 0;
    string ans = "AGC";
    cin >> a;

    if(a<1200){
        ans = "ABC";
    }else if (a <2800){
        ans = "ARC";
    }

    cout << ans << endl;
}
};


int main() {
	ARatedForMe solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
