/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class BSnakeToy {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int N,K,L[100009];
    int ans = 0;
    cin >> N >> K;
    for(int i = 0; i < N; i++) cin >> L[i];
    sort(L, L+N, greater<int>());
    for(int i = 0; i < K; i++) ans += L[i];
    cout << ans << endl;
}
};


int main() {
	BSnakeToy solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
