/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class AHappyBirthday {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a,b;
    string ans;
    cin >> a >> b;
    if(a<=8 && b<=8){
        ans = "Yay!";
    } else{
        ans = ":(";
    }
    cout << ans << endl;
}
};


int main() {
	AHappyBirthday solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
