/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>

class AGarden {
public:
	void solve(std::istream& in, std::ostream& out) {
        int a, b;
	    std::cin >> a >> b;
	    std::cout << (a-1)*(b-1) << std::endl;
	}
};


int main() {
	AGarden solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
