/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>


using namespace std;
typedef long long unsigned int ll;

#define EPS (1e-7)
#define INF (1e9)
#define PI (acos(-1))

class AAddSubMul {
public:
void solve(std::istream& cin, std::ostream& cout) {
    int a,b,arr[3];
    int ans = 0;
    cin >> a >> b;
    arr[0] = a+b;
    arr[1] = a-b;
    arr[2] = a*b;
    ans = *max_element(arr,arr+3);
    cout << ans << endl;
}
};


int main() {
	AAddSubMul solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
